M48
; DRILL file {KiCad 8.0.3} date 2024-07-03T21:16:37+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-03T21:16:37+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1024
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.624Y-3.2835
X4.624Y-4.3858
T2
X3.3957Y-3.0315
X6.9694Y-5.4152
X8.4183Y-3.0254
M30
