M48
; DRILL file {KiCad 8.0.3} date 2024-06-30T20:16:38+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-30T20:16:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X121.596Y-71.634
X121.596Y-99.634
T2
X90.316Y-65.302
X181.216Y-126.002
X218.016Y-65.302
M30
